export const nodeList = [
  {
    id: 0,
    product: "undef",
    corx: 0,
    cory: 0,
    adjacent: [1, 10],
    inBuyList: false,
  },
  {
    id: 1,
    product: "undef",
    corx: 1,
    cory: 0,
    adjacent: [2, 0, 11],
    inBuyList: false,
  },
  {
    id: 2,
    product: "undef",
    corx: 2,
    cory: 0,
    adjacent: [3, 1],
    inBuyList: false,
  },
  {
    id: 3,
    product: "undef",
    corx: 3,
    cory: 0,
    adjacent: [4, 2, 13],
    inBuyList: false,
  },
  {
    id: 4,
    product: "undef",
    corx: 4,
    cory: 0,
    adjacent: [5, 3, 14],
    inBuyList: false,
  },
  {
    id: 5,
    product: "undef",
    corx: 5,
    cory: 0,
    adjacent: [6, 4],
    inBuyList: false,
  },
  {
    id: 6,
    product: "undef",
    corx: 6,
    cory: 0,
    adjacent: [7, 5, 16],
    inBuyList: false,
  },
  {
    id: 7,
    product: "undef",
    corx: 7,
    cory: 0,
    adjacent: [8, 6, 17],
    inBuyList: false,
  },
  {
    id: 8,
    product: "undef",
    corx: 8,
    cory: 0,
    adjacent: [9, 7],
    inBuyList: false,
  },
  {
    id: 9,
    product: "undef",
    corx: 9,
    cory: 0,
    adjacent: [8, 19],
    inBuyList: false,
  },
  {
    id: 10,
    product: "undef",
    corx: 0,
    cory: 1,
    adjacent: [11, 20, 0],
    inBuyList: false,
  },
  {
    id: 11,
    product: "11",
    corx: 1,
    cory: 1,
    adjacent: [10, 21, 1],
    inBuyList: false,
  },
  {
    id: 13,
    product: "13",
    corx: 3,
    cory: 1,
    adjacent: [14, 23, 3],
    inBuyList: false,
  },
  {
    id: 14,
    product: "14",
    corx: 4,
    cory: 1,
    adjacent: [13, 24, 4],
    inBuyList: false,
  },
  {
    id: 16,
    product: "16",
    corx: 6,
    cory: 1,
    adjacent: [17, 26, 6],
    inBuyList: false,
  },
  {
    id: 17,
    product: "17",
    corx: 7,
    cory: 1,
    adjacent: [16, 27, 7],
    inBuyList: false,
  },
  {
    id: 19,
    product: "19",
    corx: 9,
    cory: 1,
    adjacent: [29, 9],
    inBuyList: false,
  },
  {
    id: 20,
    product: "undef",
    corx: 0,
    cory: 2,
    adjacent: [21, 30, 10],
    inBuyList: false,
  },
  {
    id: 21,
    product: "undef",
    corx: 1,
    cory: 2,
    adjacent: [20, 31, 11],
    inBuyList: false,
  },
  {
    id: 23,
    product: "undef",
    corx: 3,
    cory: 2,
    adjacent: [24, 33, 13],
    inBuyList: false,
  },
  {
    id: 24,
    product: "undef",
    corx: 4,
    cory: 2,
    adjacent: [23, 34, 14],
    inBuyList: false,
  },
  {
    id: 26,
    product: "undef",
    corx: 6,
    cory: 2,
    adjacent: [27, 36, 16],
    inBuyList: false,
  },
  {
    id: 27,
    product: "undef",
    corx: 7,
    cory: 2,
    adjacent: [26, 37, 17],
    inBuyList: false,
  },
  {
    id: 29,
    product: "undef",
    corx: 9,
    cory: 2,
    adjacent: [39, 19],
    inBuyList: false,
  },
  {
    id: 30,
    product: "undef",
    corx: 0,
    cory: 3,
    adjacent: [31, 40, 20],
    inBuyList: false,
  },
  {
    id: 31,
    product: "31",
    corx: 1,
    cory: 3,
    adjacent: [30, 41, 21],
    inBuyList: false,
  },
  {
    id: 33,
    product: "33",
    corx: 3,
    cory: 3,
    adjacent: [34, 43, 23],
    inBuyList: false,
  },
  {
    id: 34,
    product: "34",
    corx: 4,
    cory: 3,
    adjacent: [33, 44, 24],
    inBuyList: false,
  },
  {
    id: 36,
    product: "36",
    corx: 6,
    cory: 3,
    adjacent: [37, 46, 26],
    inBuyList: false,
  },
  {
    id: 37,
    product: "37",
    corx: 7,
    cory: 3,
    adjacent: [36, 47, 27],
    inBuyList: false,
  },
  {
    id: 39,
    product: "39",
    corx: 9,
    cory: 3,
    adjacent: [49, 29],
    inBuyList: false,
  },
  {
    id: 40,
    product: "undef",
    corx: 0,
    cory: 4,
    adjacent: [41, 50, 30],
    inBuyList: false,
  },
  {
    id: 41,
    product: "undef",
    corx: 1,
    cory: 4,
    adjacent: [40, 51, 31],
    inBuyList: false,
  },
  {
    id: 43,
    product: "undef",
    corx: 3,
    cory: 4,
    adjacent: [44, 53, 33],
    inBuyList: false,
  },
  {
    id: 44,
    product: "undef",
    corx: 4,
    cory: 4,
    adjacent: [43, 54, 34],
    inBuyList: false,
  },
  {
    id: 46,
    product: "undef",
    corx: 6,
    cory: 4,
    adjacent: [47, 56, 36],
    inBuyList: false,
  },
  {
    id: 47,
    product: "undef",
    corx: 7,
    cory: 4,
    adjacent: [46, 57, 37],
    inBuyList: false,
  },
  {
    id: 49,
    product: "undef",
    corx: 9,
    cory: 4,
    adjacent: [59, 39],
    inBuyList: false,
  },
  {
    id: 50,
    product: "undef",
    corx: 0,
    cory: 5,
    adjacent: [51, 60, 40],
    inBuyList: false,
  },
  {
    id: 51,
    product: "51",
    corx: 1,
    cory: 5,
    adjacent: [50, 61, 41],
    inBuyList: false,
  },
  {
    id: 53,
    product: "53",
    corx: 3,
    cory: 5,
    adjacent: [54, 63, 43],
    inBuyList: false,
  },
  {
    id: 54,
    product: "54",
    corx: 4,
    cory: 5,
    adjacent: [53, 64, 44],
    inBuyList: false,
  },
  {
    id: 56,
    product: "56",
    corx: 6,
    cory: 5,
    adjacent: [57, 66, 46],
    inBuyList: false,
  },
  {
    id: 57,
    product: "57",
    corx: 7,
    cory: 5,
    adjacent: [56, 67, 47],
    inBuyList: false,
  },
  {
    id: 59,
    product: "59",
    corx: 9,
    cory: 5,
    adjacent: [69, 49],
    inBuyList: false,
  },
  {
    id: 60,
    product: "undef",
    corx: 0,
    cory: 6,
    adjacent: [61, 70, 50],
    inBuyList: false,
  },
  {
    id: 61,
    product: "61",
    corx: 1,
    cory: 6,
    adjacent: [62, 60, 51],
    inBuyList: false,
  },
  {
    id: 62,
    product: "undef",
    corx: 2,
    cory: 6,
    adjacent: [63, 61],
    inBuyList: false,
  },
  {
    id: 63,
    product: "63",
    corx: 3,
    cory: 6,
    adjacent: [64, 62, 53],
    inBuyList: false,
  },
  {
    id: 64,
    product: "undef",
    corx: 4,
    cory: 6,
    adjacent: [65, 63, 54],
    inBuyList: false,
  },
  {
    id: 65,
    product: "65",
    corx: 5,
    cory: 6,
    adjacent: [66, 64],
    inBuyList: false,
  },
  {
    id: 66,
    product: "undef",
    corx: 6,
    cory: 6,
    adjacent: [67, 65, 76, 56],
    inBuyList: false,
  },
  {
    id: 67,
    product: "undef",
    corx: 7,
    cory: 6,
    adjacent: [68, 66, 77, 57],
    inBuyList: false,
  },
  {
    id: 68,
    product: "undef",
    corx: 8,
    cory: 6,
    adjacent: [69, 67, 78],
    inBuyList: false,
  },
  {
    id: 69,
    product: "undef",
    corx: 9,
    cory: 6,
    adjacent: [68, 79, 59],
    inBuyList: false,
  },
  {
    id: 70,
    product: "undef",
    corx: 0,
    cory: 7,
    adjacent: [80, 60],
    inBuyList: false,
  },
  {
    id: 76,
    product: "undef",
    corx: 6,
    cory: 7,
    adjacent: [77, 86, 66],
    inBuyList: false,
  },
  {
    id: 77,
    product: "undef",
    corx: 7,
    cory: 7,
    adjacent: [78, 76, 87, 67],
    inBuyList: false,
  },
  {
    id: 78,
    product: "78",
    corx: 8,
    cory: 7,
    adjacent: [79, 77, 68],
    inBuyList: false,
  },
  {
    id: 79,
    product: "undef",
    corx: 9,
    cory: 7,
    adjacent: [78, 89, 69],
    inBuyList: false,
  },
  {
    id: 80,
    product: "undef",
    corx: 0,
    cory: 8,
    adjacent: [81, 90, 70],
    inBuyList: false,
  },
  {
    id: 81,
    product: "81",
    corx: 1,
    cory: 8,
    adjacent: [82, 80],
    inBuyList: false,
  },
  {
    id: 82,
    product: "undef",
    corx: 2,
    cory: 8,
    adjacent: [83, 81],
    inBuyList: false,
  },
  {
    id: 83,
    product: "83",
    corx: 3,
    cory: 8,
    adjacent: [84, 82],
    inBuyList: false,
  },
  {
    id: 84,
    product: "undef",
    corx: 4,
    cory: 8,
    adjacent: [85, 83],
    inBuyList: false,
  },
  {
    id: 85,
    product: "85",
    corx: 5,
    cory: 8,
    adjacent: [86, 84],
    inBuyList: false,
  },
  {
    id: 86,
    product: "undef",
    corx: 6,
    cory: 8,
    adjacent: [87, 85, 96, 76],
    inBuyList: false,
  },
  {
    id: 87,
    product: "87",
    corx: 7,
    cory: 8,
    adjacent: [86, 97, 77],
    inBuyList: false,
  },
  {
    id: 89,
    product: "89",
    corx: 9,
    cory: 8,
    adjacent: [99, 79],
    inBuyList: false,
  },
  {
    id: 90,
    product: "undef",
    corx: 0,
    cory: 9,
    adjacent: [80],
    inBuyList: false,
  },
  {
    id: 96,
    product: "undef",
    corx: 6,
    cory: 9,
    adjacent: [97, 86],
    inBuyList: false,
  },
  {
    id: 97,
    product: "undef",
    corx: 7,
    cory: 9,
    adjacent: [98, 96, 87],
    inBuyList: false,
  },
  {
    id: 98,
    product: "98",
    corx: 8,
    cory: 9,
    adjacent: [99, 97],
    inBuyList: false,
  },
  {
    id: 99,
    product: "undef",
    corx: 9,
    cory: 9,
    adjacent: [98, 89],
    inBuyList: false,
  },
];
